default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mvp-1_development
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432

test:
  <<: *default
  database: mvp-1_test
  username: postgres
  password: postgres
  host: db
  port: 5432

production:
  primary:
    <<: *default
    adapter: postgresql
    database: mvp-1_production
    username: postgres
    password: postgres
    host: db
    port: 5432

  queue:
    <<: *default
    adapter: postgresql
    database: myapp_queue
    username: postgres
    password: postgres
    host: db
    port: 5432
  
  cache:
    <<: *default
    adapter: postgresql
    database: mvp-1_production_cache
    username: postgres
    password: postgres
    host: db
    port: 5432
