registry:
  username: chimitcyrenov
  password:
    - KAMAL_REGISTRY_PASSWORD

service: mvp-1
image: chimitcyrenov/mvp-1_web

servers:
  web:
    hosts:
      - 172.18.242.201 
    cmd: bundle exec rails server -b 0.0.0.0 -p 80 
    
accessories:
  db:
    image: postgres:16
    host: 172.18.242.201
    port: 5432
    env:
      clear:
        POSTGRES_DB: mvp_1_production
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    directories:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    host: 172.18.242.201
    port: 6379
    directories:
      - redis_data:/data

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_LEVEL: info
    REDIS_URL: redis://172.18.242.201:6379/1
    DATABASE_URL: postgresql://postgres:postgres@172.18.242.201:5432/mvp_1_production

ssh:
  user: ubuntu
  port: 22

builder:
  arch: amd64

proxy:
  healthcheck:
    interval: 15
    timeout: 120
