service: mvp-1
image: chimitcyrenov/mvp-1_web

servers:
  web:
    hosts:
      - localhost

proxy:
  ssl: false
  host: localhost

registry:
  username: chimitcyrenov
  password: <%= ENV['KAMAL_REGISTRY_PASSWORD'] %>

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: info
    REDIS_URL: redis://host.docker.internal:6379/1
    DATABASE_HOST: db
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_PORT: 5432

volumes:
  - "mvp-1_storage:/rails/storage"

builder:
  arch: amd64
  args:
    RAILS_MASTER_KEY: <%= ENV['RAILS_MASTER_KEY'] %>

ssh:
  user: and
  port: 22